"""
指標 ID (キャッシュファイル名スラッグ) → 日本語表示名のマッピング。

frontend/src/constants/countryData.tsx の code-name ペアから自動生成。
このファイルを直接編集するのではなく、countryData.tsx を更新した後に
scripts/regen_indicator_labels.py で再生成することを推奨。
"""
from __future__ import annotations

INDICATOR_LABELS: dict[str, str] = {
    'adp_employment': 'ADP雇用者数',
    'adp_wage_growth': 'ADP賃金上昇率中央値',
    'advance_real_retail_sales': '実質小売売上高',
    'affinity_spend': 'クレジット / デビットカード支出',
    'aggregate_financing': '社会融資総量',
    'anz_business_outlook_survey': 'ANZ企業景況感指数',
    'anz_business_sentiment_price': 'ANZ企業景況感物価関連',
    'anz_job_advertisements': 'ANZ求人広告',
    'asx_rate_tracker': 'Rate Tracker',
    'atlanta_fed_wage': 'アトランタ連銀賃金トラッカー',
    'australia': 'オーストラリア',
    'average_hourly_earnings': '平均時給 / 自発的離職率',
    'average_weekly_working_hours': '平均週労働時間',
    'balance_of_trade': '貿易収支',
    'balance_sheet': '中銀バランスシート',
    'baltic_dry_index': 'バルチック海運指数（BDI）',
    'bank_balance_sheet': '銀行バランスシート',
    'bank_lending': '銀行貸し出し態度',
    'bei': 'BEI（ブレークイーブン・インフレ率）',
    'beijing_pm25': '北京PM2.5濃度',
    'boc_balance_sheet': 'BOCバランスシート',
    'boc_mpr': 'BOC金融政策報告書',
    'boc_rate_cuts': 'BOC利上げ・利下げ期待',
    'boe_bank_rate': 'BOE政策金利',
    'boe_dmp_survey': 'Decision Maker Panel (DMP) サーベイ',
    'boe_economic_outlook': 'BOE経済見通し',
    'boe_mortgage_lending': '住宅ローン承認件数',
    'boe_mortgage_rates': '住宅ローン金利',
    'boe_mpc_voting': 'MPC投票履歴',
    'boe_ois_curve': 'OISカーブ',
    'boj_cai': '消費活動指数（旅行収支調整前）',
    'boj_current_account_balance': '日銀当座預金残高',
    'boj_gdp_gap': 'GDPギャップ（日銀）',
    'boj_lending': '貸出動向',
    'boj_meeting_expectations': '日銀政策金利期待',
    'boj_outlook': '経済・物価情勢の展望',
    'boj_policy_rate_chart': '政策金利',
    'boj_potential_growth': '潜在成長率（日銀）',
    'boj_tankan': '日銀短観',
    'bond_issuance': '国債発行',
    'bos': 'Business Outlook Survey（BOS）',
    'bsi': '法人企業景気予測調査',
    'btp_bund_spread': '伊独スプレッド',
    'building_permits': '建築許可件数',
    'ca_average_hourly_wage': '平均時給',
    'ca_corra': 'CORRA（翌日物レポ平均金利）',
    'ca_government_deposits': '政府預金',
    'ca_job_vacancy_rate': '求人率',
    'ca_labor_force_participation_rate': '労働参加率',
    'ca_settlement_balances': '決済残高',
    'caixin_pmi': 'Caixin PMI',
    'canada': 'カナダ',
    'canada_banks_balance_sheet': 'カナダ銀行バランスシート（チャータード銀行）',
    'capacity_utilization': '設備稼働率',
    'capital_flows': '資本フロー',
    'capital_investment': '設備投資',
    'carts': 'シカゴ連銀小売指数（CARTS）',
    'cash_earnings': '現金給与額',
    'cb_consumer_confidence': 'CB消費者信頼感指数',
    'cb_jobs_labor': 'CB雇用機会業況判断',
    'cbi_industrial_trends': 'CBI製造業受注指数',
    'cbo_projections': 'CBO経済見通し',
    'central_bank_balance_sheet': '中銀バランスシート',
    'central_parity': 'Central Parity Rate',
    'cgpi': '企業物価指数（CGPI）',
    'cgpi_food_agriculture': '企業物価指数：飲食料品 / 農林水産物',
    'ch_balance_of_trade': '貿易収支',
    'ch_consumer_sentiment': 'SECO消費者景況感',
    'ch_current_account': '経常収支',
    'ch_current_account_gdp_ratio': '経常収支対GDP比',
    'ch_growth_rate': 'GDP成長率',
    'ch_households_and_npish': '家計消費',
    'ch_hpi': '住宅価格指数',
    'ch_industrial_production': '鉱工業生産',
    'ch_job_vacancies': '求人情報',
    'ch_mortgage_balance': '住宅ローン残高',
    'ch_mortgage_rates': '住宅ローン金利',
    'ch_new_mortgage_loans': '新規住宅ローンの融資限度額の合計金額',
    'ch_nominal_wage_growth': '名目賃金上昇率',
    'ch_pmi': 'PMI（購買担当者景気指数）',
    'ch_unemployment_rate': '失業率',
    'challenger_job_cuts': 'チャレンジャー人員削減数',
    'china': '中国',
    'cn_current_account': '経常収支',
    'cn_current_account_gdp_ratio': '経常収支対GDP比',
    'cn_electronics_stock': '電気機器在庫',
    'cn_integrated_circuit_manufacturing': '集積回路生産',
    'cn_land_sales_income': '土地売却収入',
    'cn_local_bonds': '地方債',
    'cn_trade_balance': '貿易収支',
    'commercial_residential_sales': '商業住宅販売',
    'consumer': '消費',
    'consumer_confidence': '消費者信頼感指数',
    'consumer_credit': 'クレジットカードローン残高',
    'consumer_sentiment': '消費動向調査（消費者態度指数）',
    'consumer_spending': '個人消費',
    'consumption_expenditure': '実質消費支出（家計調査）',
    'container_freight_index': 'コンテナ運賃指数（SCFI/CCFI）',
    'continued_claims': '継続失業保険申請件数',
    'cotality_home_prices': 'Cotality住宅価格指数',
    'cpi': 'CPI',
    'cpi_categories': 'CPI 項目別',
    'cpi_item': 'CPI 項目別',
    'cpi_service_rent': 'CPI サービス/家賃（粘着性CPI）',
    'cre_loan_delinquency': 'CRE貸出延滞率',
    'credit_impulse': 'クレジットインパルス',
    'csce': 'Canadian Survey of Consumer Expectations（CSCE）',
    'current_account': '経常収支',
    'current_account_gdp_ratio': '経常収支対GDP比',
    'current_account_gdp_ratio"': '経常収支対GDP比',
    'debt_service_ratio': '家計債務返済比率（DSR）',
    'delinquency_rate': 'クレジットカードローン延滞率',
    'disposable_income': '可処分所得',
    'disposable_personal_income': '可処分所得',
    'dot_plot': 'Dot Plot',
    'durable_goods': '耐久財受注',
    'ecb_adjusted_loans': '貸出動向（ユーロ圏・BSI）',
    'ecb_balance_sheet': 'ECBバランスシート',
    'ecb_bank_interest_rates': '銀行金利',
    'ecb_bls': '銀行貸出調査（ユーロ圏・BLS）',
    'ecb_ces_wage_expectations': 'CES賃金期待（ユーロ圏）',
    'ecb_ciss': 'システミックストレス指標（CISS）',
    'ecb_current_account': '経常収支（ユーロ圏）',
    'ecb_employment': '雇用者数変化（ユーロ圏）',
    'ecb_gdp': 'GDP（ユーロ圏）',
    'ecb_gdp_components': 'GDP構成要素（ユーロ圏）',
    'ecb_hicp': 'HICP（ユーロ圏）',
    'ecb_hicp_breakdown': 'HICP 項目別（ユーロ圏）',
    'ecb_inflation_expectations': 'インフレ期待 / CES（ユーロ圏）',
    'ecb_labor_productivity': '労働生産性（ユーロ圏）',
    'ecb_m3': 'M3マネーサプライ',
    'ecb_macro_projections': 'マクロ経済予測',
    'ecb_negotiated_wages': '交渉妥結賃金（ユーロ圏）',
    'ecb_policy_framework': 'ECB政策枠組み',
    'ecb_ppi': 'PPI（ユーロ圏）',
    'ecb_production': '鉱工業生産（ユーロ圏）',
    'ecb_rate_cuts': 'ECB利上げ・利下げ期待',
    'ecb_rates': 'ECB預金ファシリティ金利',
    'ecb_retail_trade': '小売売上高（ユーロ圏）',
    'ecb_spf': 'インフレ期待 / SPF（ユーロ圏）',
    'ecb_spf_core': 'コアインフレ期待 / SPF（ユーロ圏）',
    'ecb_unemployment_chart': '失業率（ユーロ圏）',
    'ecb_unit_labour_cost': '労働コスト指数（ユーロ圏）',
    'economic_forecast': '経済見通し（MPS）',
    'economic_surprise_index': 'エコノミックサプライズ指数',
    'economy': '経済',
    'economy_watcher': '景気ウォッチャー調査',
    'empire_state': 'NY連銀製造業景気指数',
    'employment': '雇用',
    'employment_change': '雇用者数変化',
    'employment_cost_index': '雇用コスト指数',
    'employment_type': '雇用形態別労働者過不足判断D.I.',
    'epu': '経済政策不確実性指数（EPU）',
    'eu_government_debt_to_gdp_ratio': '政府債務残高対GDP比（ユーロ圏）',
    'eu_import_prices': '輸入物価（ユーロ圏）',
    'eu_international_trade': '国際貿易（ユーロ圏）',
    'eu_terms_of_trade': '交易条件（ユーロ圏）',
    'eurex_ois': '3ヶ月ユーロSTR先物カーブ',
    'euro_policy_uncertainty': '欧州経済政策不確実性指数',
    'eurostat_consumer_confidence': '消費者信頼感指数（ユーロ圏）',
    'eurostat_esi': 'ESI（ユーロ圏・主要国）',
    'eurostat_job_vacancy': '求人率（ユーロ圏）',
    'eurostat_wages': '賃金上昇率（ユーロ圏）',
    'eurozone': 'ユーロ圏',
    'existing_home_sales': '中古住宅販売',
    'fci': 'FCI-G（金融情勢指数）',
    'fed_watch': 'Fed Watch',
    'federal_budget': '連邦財政収支',
    'fixed_asset_investment': '固定資産投資',
    'fixing_repo_rate': 'Fixing Repo Rate',
    'fomc_projections': 'FOMC経済見通し',
    'foreign_currency_reserves': '外貨準備',
    'forex_reserves': '外貨準備',
    'france_business_confidence': '企業信頼感（フランス）',
    'france_pmi': 'PMI（フランス）',
    'frb_total_assets': 'FRB総資産',
    'fullpart_time': 'フルタイム / パートタイム雇用者数',
    'fulltime_parttime': 'フルタイム/パートタイム',
    'gdp': 'GDP',
    'gdp_components': 'GDP構成要素（前期比）',
    'gdp_components_growth': 'GDP項目別成長率',
    'gdp_contributions': 'GDP寄与度',
    'gdp_deflator': 'GDPデフレーター',
    'gdp_gap': 'GDPギャップ（内閣府）',
    'gdp_growth': 'GDP成長率',
    'gdp_monthly': '月次GDP',
    'gdp_price_related': 'GDP詳細',
    'gdpnow': 'GDPNow',
    'germany_consumer_confidence_gfk': '消費者信頼感指数（ドイツ・GfK）',
    'germany_cpi': 'CPI（ドイツ）',
    'germany_factory_orders': '製造業新規受注（ドイツ）',
    'germany_gdp_growth': 'GDP成長率（ドイツ）',
    'germany_industrial_production': '鉱工業生産（ドイツ）',
    'germany_pmi': 'PMI（ドイツ）',
    'germany_ppi': 'PPI（ドイツ）',
    'germany_retail_sales': '小売売上高（ドイツ）',
    'germany_unemployment': '失業率（ドイツ）',
    'global': 'グローバル',
    'global_manufacturing_pmi': 'グローバル製造業PMI',
    'gscpi': 'GSCPI',
    'halifax_house_price': 'ハリファックス住宅価格指数',
    'house_price_index': '住宅価格指数',
    'household_saving_ratio': '家計貯蓄率',
    'household_spending': '家計支出',
    'housing': '住宅',
    'housing_indicators': 'Zillow住宅価値指数 / ケースシラー住宅価格指数 / 家賃CPI',
    'housing_lending_rates': '住宅ローン金利',
    'housing_loan_arrears': '住宅ローン延滞率',
    'housing_starts': '住宅着工件数',
    'housing_starts_permits': '住宅着工件数 / 建設許可件数',
    'hpi': '住宅価格指数',
    'ifo_business_climate': 'IFO企業景況感指数（ドイツ）',
    'iip': '鉱工業生産',
    'iip_forecast': '鉱工業生産予測指数',
    'import_export_price': '輸入物価指数 / 輸出物価指数',
    'indeed_euro_wage': 'Indeed賃金トラッカー（ユーロ圏）',
    'indeed_wage_tracker': 'Indeed賃金トラッカー',
    'industrial_production': '鉱工業生産',
    'inflation': '物価',
    'inflation_expectations': 'インフレ期待',
    'inflation_forecast': 'SNBインフレ見通し',
    'inflation_nowcasting': 'インフレーションナウキャスティング',
    'initial_claims': '新規失業保険申請件数',
    'ippi': 'IPPI（工業製品価格指数）',
    'ism_components': 'ISM製造業サブインデックス',
    'ism_manufacturing': 'ISM製造業景況指数',
    'ism_non_manufacturing': 'ISM非製造業景況指数',
    'ism_non_manufacturing_components': 'ISM非製造業サブインデックス',
    'ivey_pmi': 'Ivey PMI',
    'japan': '日本',
    'japan_balance_sheet': '日銀バランスシート',
    'job_offers': '有効求人倍率',
    'job_openings_per_unemployed': '求人倍率',
    'job_vacancies': '求人件数',
    'jolts_hires_layoffs': 'JOLTS採用数 / 解雇数',
    'jolts_indeed': 'JOLTS求人 / Indeed求人件数',
    'kof_barometer': 'KOF経済バロメーター',
    'komatrax': 'Komatrax（車両稼働時間）',
    'korea_exports': '韓国輸出',
    'korea_semiconductor_exports': '韓国半導体輸出',
    'labor_cost_index': '労働コスト指数',
    'labor_force_participation': '労働参加率',
    'labour_force_participation': '労働参加率',
    'li_keqiang_index': '李克強指数',
    'lpr': 'LPR',
    'm1_m2': 'M1/M2',
    'machine_tool_orders': '工作機械受注',
    'machinery_orders': '機械受注（船舶・電力を除く民需）',
    'machinery_orders_forecast': '機械受注予測・達成率',
    'manufacturing_pmi_sub': '製造業PMIサブ',
    'median_cpi': 'Median CPI / 16% Trimmed Mean',
    'michigan_consumer_sentiment': 'ミシガン消費者信頼感指数',
    'michigan_inflation_expectations': 'ミシガンインフレ期待',
    'mortgage_rates': 'フレディ・マック30年固定住宅ローン金利',
    'multiple_jobs_parttime': '複数の仕事を持つ人 / 経済的理由によるパートタイム',
    'nab_business_confidence': 'NAB企業信頼感指数',
    'nab_cost_price': 'NAB企業調査（コスト・価格）',
    'nahb_hmi': 'NAHB住宅市場指数',
    'national_cpi': '全国CPI',
    'nationwide_hpi': 'ネーションワイド住宅価格指数',
    'ner_pulse': 'ADP雇用者数（NER Pulse）',
    'new_home_sales': '新築住宅販売',
    'new_housing_price_index': '新築住宅価格指数',
    'new_rmb_loans': '新規人民元貸出',
    'newzealand': 'ニュージーランド',
    'nfci': '金融環境指数（NFCI）',
    'nfib': 'NFIB中小企業楽観指数',
    'nfib_capex': 'NFIB設備投資計画',
    'nfib_compensation': 'NFIB人件費 / 雇用計画',
    'nfib_compensation_unemployment': 'NFIB労働報酬 / 失業率',
    'non_manufacturing_pmi_sub': '非製造業PMIサブ',
    'nonfarm_payrolls': '非農業部門雇用者数',
    'number_of_employees': '雇用者数',
    'ny_inflation_expectations': 'NYインフレ期待',
    'nz_capacity_utilization': '設備稼働率',
    'nz_current_account_balance': '経常収支',
    'nz_current_account_gdp_ratio': '経常収支対GDP比',
    'nz_gdp_growth_rate': 'GDP成長率',
    'nz_gdp_item': 'GDP項目',
    'nz_global_dairy_trade': '乳製品価格（GDT）',
    'nz_pmi': 'PMI / PSI / PCI',
    'nz_terms_of_trade': '交易条件',
    'nz_trade_balance': '貿易収支',
    'nzier_business_conditions': 'NZIER企業景況指数',
    'oas': 'OAS（スプレッド）',
    'oecd_cli': 'OECD CLI（景気先行指数）',
    'ois_curve_chart': 'OISカーブ',
    'on_rrp': 'ON RRP',
    'ons_gdp': 'GDP成長率',
    'ons_gva': '月間GDP（GVA）',
    'ons_production': '鉱工業生産',
    'opentable': 'レストラン予約件数',
    'order_inventory_balance': 'ISM受注在庫バランス',
    'overseas_investor_flow': '海外投資家フロー',
    'overtime_hours': '平均残業時間',
    'participation_rate': '労働参加率',
    'pce': '個人消費支出（PCE）',
    'pce_deflator': 'PCEデフレーター',
    'pce_food_recreation': 'PCEデフレーター飲食宿泊・娯楽',
    'pending_home_sales': '中古住宅販売保留',
    'personal_income': '個人所得',
    'personal_saving_rate': '家計貯蓄率',
    'philadelphia_fed': 'フィラデルフィア連銀製造業景気指数',
    'pmi': 'PMI',
    'policy': '金融政策',
    'policy_rate': '政策金利',
    'pos_uvpi': 'POS-UVPI（消費者購買単価指数）',
    'potential_gdp': '潜在成長率',
    'potential_growth': '潜在成長率（内閣府）',
    'ppi': 'PPI',
    'ppi_categories': 'PPI PCE関連項目',
    'price_pass_through_rate': '価格転嫁率',
    'private_capex': '民間設備投資',
    'quarterly_cpi': '四半期CPI',
    'quarterly_gdp': 'GDP成長率',
    'quarterly_refunding': 'Quarterly Refunding',
    'rba_expectations': '利上げ・利下げ期待',
    'rba_monetary_policy': 'RBA経済予測',
    'rba_ois': 'OIS',
    'rba_statement': 'RBA声明',
    'rbnz_statement': 'RBNZ声明',
    'real_wage': '実質賃金',
    'redbook': 'レッドブック（前年比）',
    'redfin_case_shiller': 'Redfin住宅価格中央値 / ケースシラー住宅価格指数',
    'rental_vacancy_rate': '賃貸空室率',
    'reserve_balances': '準備預金残高',
    'retail_food_services_price': 'シカゴ連銀小売物価指数',
    'retail_sales': '小売売上高',
    'reverse_repo_rate': 'リバースレポ金利',
    'rics_house_price': 'RICS住宅価格バランス',
    'rightmove_house_price': 'ライトムーブ住宅価格指数',
    'rrr': '預金準備率',
    'sahm_rule': 'サームルール',
    'scheduled_wage': '所定内給与',
    'scheduled_wage_common': '所定内給与（共通事業所）',
    'semiconductor_sales': '半導体売上高',
    'shibor': 'SHIBOR',
    'shuntou': '春闘',
    'sight_deposits': 'SNB当座預金',
    'slos': 'Senior Loan Officer Survey（SLOS）',
    'sofr_volatility': 'SOFR / ボラティリティ',
    'sonia': 'SONIA',
    'sp_pmi': 'S&P Global PMI',
    'sp_pmi_chart': 'S&P Global PMI',
    'spain_hicp_cpi': 'CPI / HICP（スペイン）',
    'sppi': '企業向けサービス価格指数（SPPI）',
    'switzerland': 'スイス',
    'taiwan_electronics_exports': '台湾電気機器輸出',
    'taiwan_export_orders': '台湾輸出受注',
    'taiwan_manufacturing_pmi': '台湾製造業PMI',
    'taiwan_pmi_outlook': '台湾PMI先行き（電子工学業）',
    'temporary_help_services': '臨時就業者数',
    'term_premium': 'タームプレミアム',
    'terms_of_trade': '交易条件',
    'tertiary_industry_index': '第三次産業活動指数',
    'tga': 'TGA（財務省一般勘定）',
    'tokyo_cpi': '東京CPI',
    'total_number_of_people': '人流総量',
    'total_vehicle_sales': '自動車販売台数',
    'trade_balance': '貿易収支',
    'trimmed_mean_pce': 'Trimmed Mean PCE',
    'truflation_us_cpi': 'Truflation US CPI',
    'tsa_checkpoint': '航空機旅客者数',
    'uk': 'イギリス',
    'uk_boe_inflation_attitudes': 'インフレ期待調査',
    'uk_brc_retail_sales': 'BRC小売売上高',
    'uk_brc_shop_price': 'BRC店頭価格指数',
    'uk_claimant_count': '失業保険申請件数',
    'uk_cpi_components': 'CPI 項目別',
    'uk_cpih': 'CPI',
    'uk_current_account': '経常収支',
    'uk_current_account_gdp_ratio': '経常収支対GDP比',
    'uk_economic_activity': '経済活動率',
    'uk_employment': '雇用者数',
    'uk_gfk_consumer_confidence': 'GfK消費者信頼感指数',
    'uk_government_debt_to_gdp_ratio': '政府債務残高対GDP比',
    'uk_house_price': '国家統計局住宅価格指数',
    'uk_indeed_wage_tracker': 'Indeed賃金トラッカー',
    'uk_ppi': 'PPI',
    'uk_public_sector_net_borrowing': '公的部門純借入',
    'uk_qt': 'APFギルト保有残高（QT）',
    'uk_real_wages': '実質平均週給',
    'uk_retail_sales': '小売売上高',
    'uk_trade_balance': '貿易収支',
    'uk_unemployment': '失業率',
    'uk_wages': '平均週給',
    'underutilization': 'アンダー・ユーティライゼーション',
    'unemployment': '失業率',
    'unemployment_by_reason': '失業率内訳',
    'unemployment_rate': '失業率',
    'unit_labor_cost': '単位労働コスト / 労働生産性',
    'us_export_dependence': '米国輸出依存度',
    'us_flights': '航空機便数',
    'usa': 'アメリカ',
    'visa_spending': 'Visa支出モメンタム指数',
    'wage_price_index': '賃金物価指数',
    'wages': '賃金',
    'zew_economic_sentiment': 'ZEW景況感指数（ドイツ）',
    'zillow_rent_cpi': 'Zillow家賃指数 / 家賃CPI',
}


try:
    from backend.services.dashboard.indicator_labels_manual import (
        INDICATOR_LABELS_MANUAL,
    )
except ImportError:
    try:
        from services.dashboard.indicator_labels_manual import (  # type: ignore
            INDICATOR_LABELS_MANUAL,
        )
    except ImportError:
        INDICATOR_LABELS_MANUAL = {}


def get_indicator_label(indicator_id: str) -> str | None:
    """指標IDから日本語ラベルを取得。未登録なら None を返す。

    優先順位: 手動辞書 > 自動生成辞書。
    手動辞書は countryData.tsx から自動抽出できない
    キャッシュファイル名をカバーするために使う。
    """
    return INDICATOR_LABELS_MANUAL.get(indicator_id) or INDICATOR_LABELS.get(indicator_id)
