"""
キャッシュファイル名ベースの指標ラベル手動マッピング。

countryData.tsx から自動抽出できないキャッシュファイル名に対して、
日本語表示ラベルを手動で追加する。

命名規約:
- キャッシュファイル名の stem から末尾の '_cache' を除いたものをキー
- 例: data/cache/usa/consumer/carts_price_cache.json → 'carts_price'
"""
from __future__ import annotations

INDICATOR_LABELS_MANUAL: dict[str, str] = {
    # ---------- USA ----------
    "carts_price": "CARTS 食料品価格",
    "carts_weekly": "CARTS 週次小売",
    "carts_schedule": "CARTS スケジュール",
    "retail_control": "小売コントロール",
    "gscpi": "GSCPI(グローバル供給網圧迫指数)",
    "nfib_optimism": "NFIB中小企業楽観指数",
    "nfib_capex": "NFIB 設備投資計画",
    "nfib_compensation": "NFIB 人件費計画",
    "nfib_compensation_unemployment": "NFIB 人件費 / 失業率",
    "nfib_actual_compensation": "NFIB 実際の人件費",
    "core_cpi": "コアCPI",
    "cpi": "CPI",
    "core_pce_deflator": "コアPCEデフレーター",
    "trimmed_mean_pce": "Trimmed Mean PCE",
    "ppi": "PPI",
    "ppi_categories": "PPI 項目別",
    "rent_cpi": "家賃CPI",
    "zillow_rent_cpi": "Zillow 家賃指数 / 家賃CPI",
    "michigan_inflation_expectations": "ミシガン インフレ期待",
    "ny_inflation_expectations": "NY連銀 インフレ期待",
    "inflation_nowcasting": "インフレナウキャスティング",
    "housing_indicators": "住宅指標(Zillow/ケースシラー/家賃CPI)",
    "ner_pulse": "ADP雇用者数 (NER Pulse)",
    "ner_pulse_schedule": "NER Pulse スケジュール",
    "jolts_hires_layoffs": "JOLTS 採用数 / 解雇数",
    "jolts_indeed": "JOLTS / Indeed求人",
    "job_openings_per_unemployed": "求人倍率",
    "challenger_job_cuts": "チャレンジャー人員削減数",
    "adp_employment": "ADP雇用者数",
    "adp_wage_growth": "ADP賃金上昇率中央値",
    "nonfarm_payrolls": "非農業部門雇用者数",
    "unemployment_by_reason": "失業率内訳",
    "unit_labor_cost": "単位労働コスト / 労働生産性",
    "overtime_hours": "平均残業時間",
    "average_hourly_earnings": "平均時給 / 自発的離職率",
    "multiple_jobs_parttime": "複数の仕事を持つ人 / 経済的理由のパートタイム",
    "fullpart_time": "フルタイム / パートタイム雇用者数",
    "us_average_weekly_working_hours": "平均週労働時間",
    "sahm_rule": "サームルール",
    "rental_vacancy_rate": "賃貸空室率",
    "ism_manufacturing": "ISM製造業景況指数",
    "ism_non_manufacturing": "ISM非製造業景況指数",
    "sp_pmi": "S&P Global PMI",
    "industrial_production": "鉱工業生産",
    "capacity_utilization": "設備稼働率",
    "nfci": "金融環境指数(NFCI)",
    "oas_hy_spread": "OAS HY スプレッド",
    "oas_ig_spread": "OAS IG スプレッド",
    "oas_hy_yield": "OAS HY 利回り",
    "tga": "TGA(財務省一般勘定)",
    "sofr_volatility": "SOFR ボラティリティ",
    "reserve_balances": "準備預金残高",
    "on_rrp": "ON RRP",
    "freddie_mac_mortgage_rates": "Freddie Mac 30年固定住宅ローン金利",
    "case_shiller": "ケースシラー住宅価格指数",
    "nahb_hmi": "NAHB住宅市場指数",
    "continued_claims": "継続失業保険申請件数",
    "initial_claims": "新規失業保険申請件数",
    "cb_jobs_labor_differential": "CB雇用機会差分",
    "indeed_wage_tracker": "Indeed 賃金トラッカー",
    "atlanta_fed_wage": "アトランタ連銀 賃金トラッカー",
    "import_export_price": "輸入物価指数 / 輸出物価指数",
    "pce_food_recreation": "PCEデフレーター 飲食宿泊・娯楽",
    "labor_force_participation": "労働参加率",
    "median_cpi": "Median CPI / 16% Trimmed Mean",
    "employment_cost_index": "雇用コスト指数",
    "us_flights": "航空機便数",
    "opentable": "レストラン予約件数",
    "disposable_income": "可処分所得",
    "personal_income": "個人所得",
    "retail_sales": "小売売上高",
    "advance_real_retail_sales": "実質小売売上高",
    "pce": "個人消費支出(PCE)",
    "cb_consumer_confidence": "CB消費者信頼感指数",
    "redbook": "レッドブック(前年比)",
    "visa_spending": "Visa支出モメンタム指数",
    "affinity_spend": "クレジット / デビットカード支出",
    "cre_loan_delinquency": "CRE貸出延滞率",
    "federal_budget": "連邦財政収支",
    "delinquency_rate": "クレジットカードローン延滞率",
    "consumer_credit": "クレジットカードローン残高",
    "total_vehicle_sales": "自動車販売台数",
    "cpi_item": "CPI 項目別",
    "fomc_table1": "FOMC Table 1",
    "fomc_projections": "FOMC経済見通し",
    "frb_total_assets": "FRB総資産",
    "cbo_projections": "CBO経済見通し",
    "ny_fed_sce_schedule": "NY連銀 SCE スケジュール",
    # ---------- Canada ----------
    "ca_cpi": "CPI",
    "ca_ippi": "IPPI(工業製品価格指数)",
    "ca_employment": "雇用者数",
    "ca_unemployment_rate": "失業率",
    "ca_average_hourly_wage": "平均時給",
    "ca_weekly_average_salary": "週平均賃金",
    "ca_job_vacancy_rate": "求人率",
    "ca_labor_force_participation_rate": "労働参加率",
    "ca_sp_pmi": "S&P Global PMI",
    "ca_ivey_pmi": "Ivey PMI",
    "ca_gdp_monthly": "月次GDP",
    "ca_gdp_growth": "GDP成長率",
    "ca_industrial_production": "鉱工業生産",
    "ca_current_account": "経常収支",
    "ca_current_account_gdp_ratio": "経常収支対GDP比",
    "ca_trade_balance": "貿易収支",
    "ca_us_export_dependence": "米国輸出依存度",
    "ca_inflation_expectations": "インフレ期待",
    "ca_csce": "CSCE(消費者期待調査)",
    "ca_bos": "Business Outlook Survey(BOS)",
    "ca_retail_sales": "小売売上高",
    "ca_housing_starts": "住宅着工件数",
    "ca_building_permits": "建設許可件数",
    "ca_new_housing_price_index": "新築住宅価格指数",
    "ca_debt_service_ratio": "家計債務返済比率(DSR)",
    "ca_settlement_balances_daily": "決済残高",
    "ca_government_deposits": "政府預金",
    "ca_corra": "CORRA(翌日物レポ平均金利)",
    "ca_boc_rate": "BOC政策金利",
    "ca_boc_balance_sheet": "BOCバランスシート",
    "ca_boc_mpr": "BOC金融政策報告書",
    "ca_canada_banks_balance_sheet": "カナダ銀行バランスシート",
    # ---------- UK ----------
    "sonia": "SONIA",
    "halifax_house_price": "ハリファックス住宅価格指数",
    "rightmove_house_price": "ライトムーブ住宅価格指数",
    "nationwide_hpi": "ネーションワイド住宅価格指数",
    "rics_house_price": "RICS住宅価格バランス",
    "boe_bank_rate": "BOE政策金利",
    "boe_ois_curve": "OISカーブ",
    "boe_mpc_voting": "MPC投票履歴",
    "boe_dmp_survey": "Decision Maker Panel (DMP)",
    "boe_mortgage_rates": "住宅ローン金利",
    "boe_mortgage_lending": "住宅ローン融資",
    "boe_inflation_attitudes": "インフレ期待調査",
    "uk_cpih": "CPI",
    "uk_cpi_components": "CPI 項目別",
    "uk_ppi": "PPI",
    "uk_retail_sales": "小売売上高",
    "uk_brc_retail_sales": "BRC小売売上高",
    "uk_brc_shop_price": "BRC店頭価格指数",
    "uk_cbi_industrial_trends": "CBI製造業受注指数",
    "uk_unemployment": "失業率",
    "uk_employment": "雇用者数",
    "uk_wages": "平均週給",
    "uk_real_wages": "実質平均週給",
    "uk_claimant_count": "失業保険申請件数",
    "uk_gfk_consumer_confidence": "GfK消費者信頼感指数",
    "uk_indeed_wage_tracker": "Indeed賃金トラッカー",
    "uk_trade_balance": "貿易収支",
    "uk_current_account": "経常収支",
    "uk_current_account_gdp_ratio": "経常収支対GDP比",
    "uk_economic_activity": "経済活動量",
    "uk_house_price": "英国統計局住宅価格指数",
    "uk_public_sector_net_borrowing": "公的部門純借入",
    "uk_government_debt_to_gdp_ratio": "政府債務対GDP比",
    "uk_qt": "APFギルト保有残高(QT)",
    "ons_gdp": "GDP成長率",
    "ons_gva": "月間GDP(GVA)",
    "ons_production": "鉱工業生産",
    # ---------- Eurozone ----------
    "m3": "M3マネーサプライ",
    "ecb_m3": "M3マネーサプライ",
    "esi": "ESI(ユーロ圏・主要国)",
    "eu_pmi": "PMI(ユーロ圏)",
    "france_pmi": "PMI(フランス)",
    "germany_pmi": "PMI(ドイツ)",
    "france_business_confidence": "企業信頼感(フランス)",
    "ifo_business_climate": "IFO企業景況感指数(ドイツ)",
    "zew_economic_sentiment": "ZEW景況感指数(ドイツ)",
    "germany_factory_orders": "製造業新規受注(ドイツ)",
    "germany_industrial_production": "鉱工業生産(ドイツ)",
    "germany_retail_sales": "小売売上高(ドイツ)",
    "germany_cpi": "CPI(ドイツ)",
    "germany_ppi": "PPI(ドイツ)",
    "germany_gdp_growth": "GDP成長率(ドイツ)",
    "germany_unemployment": "失業率(ドイツ)",
    "germany_consumer_confidence_gfk": "消費者信頼感指数(ドイツ・GfK)",
    "spain_hicp_cpi": "CPI / HICP(スペイン)",
    "eurex_ois": "3ヶ月ユーロSTR先物カーブ",
    "eurostat_esi": "ESI(ユーロ圏)",
    "eurostat_consumer_confidence": "消費者信頼感指数(ユーロ圏)",
    "eurostat_job_vacancy": "求人率(ユーロ圏)",
    "eurostat_wages": "賃金上昇率(ユーロ圏)",
    "ecb_hicp": "HICP(ユーロ圏)",
    "ecb_hicp_breakdown": "HICP 項目別(ユーロ圏)",
    "ecb_ppi": "PPI(ユーロ圏)",
    "ecb_gdp": "GDP(ユーロ圏)",
    "ecb_gdp_components": "GDP構成要素(ユーロ圏)",
    "ecb_production": "鉱工業生産(ユーロ圏)",
    "ecb_retail_trade": "小売売上高(ユーロ圏)",
    "ecb_employment": "雇用者数変化(ユーロ圏)",
    "ecb_current_account": "経常収支(ユーロ圏)",
    "ecb_negotiated_wages": "労使合意賃金(ユーロ圏)",
    "ecb_labor_productivity": "労働生産性(ユーロ圏)",
    "ecb_unit_labour_cost": "労働コスト指数(ユーロ圏)",
    "ecb_adjusted_loans": "貸出調整(ユーロ圏・BSI)",
    "ecb_bank_interest_rates": "銀行金利",
    "ecb_bls": "銀行貸出調査(ユーロ圏・BLS)",
    "ecb_spf": "インフレ期待 / SPF(ユーロ圏)",
    "ecb_spf_core": "コアインフレ期待 / SPF(ユーロ圏)",
    "ecb_ces_wage_expectations": "CES賃金期待(ユーロ圏)",
    "ecb_inflation_expectations": "インフレ期待 / CES(ユーロ圏)",
    "ecb_ciss": "システミックストレス指標(CISS)",
    "ecb_macro_projections": "マクロ経済予測",
    "ecb_balance_sheet": "ECBバランスシート",
    "ecb_rate_cuts": "ECB利上げ・利下げ予想",
    "ecb_mir_schedule": "ECB MIR スケジュール",
    "indeed_euro_wage": "Indeed賃金トラッカー(ユーロ圏)",
    "euro_policy_uncertainty": "欧州経済政策不確実性指数",
    "eu_international_trade": "国際貿易(ユーロ圏)",
    "eu_import_prices": "輸入物価(ユーロ圏)",
    "eu_terms_of_trade": "交易条件(ユーロ圏)",
    "eu_government_debt_to_gdp_ratio": "政府債務対GDP比(ユーロ圏)",
    "btp_bund_spread": "伊独スプレッド",
    # ---------- Japan ----------
    "jp_pmi": "PMI",
    "japan_capacity_utilization": "設備稼働率",
    "japan_iip": "鉱工業生産",
    "japan_iip_forecast": "鉱工業生産予測指数",
    "japan_iip_yoy": "鉱工業生産(前年比)",
    "japan_pos_uvpi": "POS-UVPI(消費者購入単価指数)",
    "japan_gdp_gap": "GDPギャップ(内閣府)",
    "japan_price_di_spread": "価格転嫁率(DIスプレッド)",
    "japan_import_export_price": "輸入 / 輸出物価指数",
    "japan_cgpi": "企業物価指数(CGPI)",
    "japan_cgpi_food_agriculture": "企業物価指数:食料品 / 農林水産物",
    "japan_sppi": "企業向けサービス価格指数(SPPI)",
    "japan_current_account": "経常収支",
    "japan_balance_of_trade": "貿易収支",
    "national_cpi_categories": "全国CPI項目別",
    "boj_policy_rate_chart": "政策金利",
    "jscc_ois_curve": "JSCC OIS カーブ",
    "scheduled_wage_estat": "所定内給与(共通事業所)",
    "job_offers_ratio": "有効求人倍率",
    # ---------- China ----------
    "cn_gold_reserves_service": "中国金準備",
    "cn_capital_flows": "資本フロー",
    "cn_overseas_investor_flow": "海外投資家フロー",
    "cn_caixin_pmi": "Caixin PMI",
    "cn_house_price_index": "住宅価格指数",
    "cn_lpr_5y": "LPR 5年",
    "cn_lpr_1y": "LPR 1年",
    "cn_local_bonds": "地方債",
    # ---------- Australia ----------
    "abs_quarterly_ppi": "ABS 四半期PPI",
    "abs_quarterly_cpi": "ABS 四半期CPI",
    "abs_monthly_cpi": "ABS 月次CPI",
    "abs_cpi_categories": "CPI項目別",
    "nab_imported_pdfs": "NAB企業調査PDF",
    "au_housing_loan_arrears": "住宅ローン延滞率",
    "rate_tracker": "Rate Tracker",
    "au_housing_lending_rates": "住宅ローン金利",
    "au_underutilization": "アンダーユーティライゼーション",
    "au_terms_of_trade": "交易条件",
    "au_pmi": "PMI",
    "au_current_account_gdp_ratio": "経常収支対GDP比",
    "au_current_account": "経常収支",
    "au_international_trade": "国際貿易",
    "au_cotality_home_prices": "Cotality住宅価格指数",
    "au_number_of_building_permits": "建設許可件数",
    "au_gdp_price_related": "GDP詳細",
    "au_gdp_economic_related": "GDP経済関連",
    "au_gdp_growth_rate": "GDP成長率",
    "au_household_saving_ratio": "家計貯蓄率",
    "au_consumer_spending": "個人消費",
    "au_nab_business_confidence": "NAB企業信頼感指数",
    "au_westpac_consumer_confidence": "Westpac消費者信頼感指数",
    "au_household_spending": "家計支出",
    "au_anz_job_advertisements": "ANZ求人広告",
    "au_job_vacancies": "求人件数",
    "au_wage_price_index": "賃金物価指数",
    "au_participation_rate": "労働参加率",
    "au_fulltime_parttime": "フルタイム/パートタイム",
    "au_employed_persons": "雇用者数",
    "au_unemployment_rate": "失業率",
    "au_inflation_expectations": "インフレ期待",
    "rba_smp_forecast": "RBA経済予測",
    "au_rba_rate": "RBA政策金利",
    # ---------- New Zealand ----------
    "nz_cpi": "CPI",
    "nz_ppi": "PPI",
    "nz_trade_balance": "貿易収支",
    "nz_terms_of_trade": "交易条件",
    "nz_gdp_item": "GDP項目",
    "nz_gdp_growth_rate": "GDP成長率",
    "nz_pci": "PCI",
    "nz_psi": "PSI",
    "nz_pmi": "PMI / PSI / PCI",
    "nz_global_dairy_trade": "乳製品価格(GDT)",
    "nz_capacity_utilization": "設備稼働率",
    "nz_nzier_business_conditions": "NZIER企業景況指数",
    "nz_anz_business_outlook_survey": "ANZ企業景況感指数",
    "nz_retail_sales": "小売売上高",
    "nz_labor_cost_index": "労働コスト指数",
    "nz_labour_force_participation": "労働参加率",
    "nz_wages": "賃金",
    "nz_number_of_employees": "雇用者数",
    "nz_unemployment_rate": "失業率",
    "test_unemp": "テスト: 失業率",
    "test_response": "テスト: レスポンス",
    "nz_inflation_expectations": "インフレ期待",
    "nz_traded_nontraded": "貿易財 / 非貿易財",
    "nz_cpi_item": "CPI項目別",
    "nz_central_bank_balance_sheet": "中銀バランスシート",
    "nz_bank_balance_sheet": "銀行バランスシート",
    "nz_mps_forecast": "経済見通し(MPS)",
    "nz_rbnz_rate": "RBNZ政策金利",
    # ---------- Switzerland ----------
    "ch_current_account_gdp_ratio": "経常収支対GDP比",
    "ch_current_account": "経常収支",
    "ch_balance_of_trade": "貿易収支",
    "ch_pmi": "PMI(購買担当者景気指数)",
    "ch_industrial_production": "鉱工業生産",
    "ch_growth_rate": "GDP成長率",
    "ch_households_and_npish": "家計消費",
    "ch_housing_prices": "住宅価格",
    "ch_hpi": "住宅価格指数",
    "ch_mortgage_rates": "住宅ローン金利",
    "ch_mortgage_balance": "住宅ローン残高",
    "ch_new_mortgage_loans": "新規住宅ローンの融資限度額の合計金額",
    "snb_schedule": "SNB スケジュール",
    "ch_unemployment_rate": "失業率",
    "ch_job_vacancies": "求人情報",
    "ch_nominal_wage_growth": "名目賃金上昇率",
    "ch_consumer_sentiment": "SECO消費者景況感",
    "kof_barometer": "KOF経済バロメーター",
    "ch_retail_trade": "小売売上高",
    "kof_economic_barometer": "KOF経済バロメーター",
    "ch_cpi": "CPI",
    "ch_ppi": "PPI",
    "foreign_currency_reserves": "外貨準備",
    "monetary_aggregate_m2": "マネーアグリゲート M2",
    "monetary_base": "マネタリーベース",
    "snb_balance_sheet": "SNBバランスシート",
    "snb_sight_deposits": "SNB要求払預金",
    "ch_inflation_forecast": "SNB インフレ見通し",
    "ch_snb_rate": "SNB政策金利",
}
